### ISSUE TITLE
Tracking: Add Commands

### ISSUE THREAD

**Issue by Snowiiii** [Pumpkin-MC/Pumpkin#15]
Our goal is to implement all Vanilla Commands. Im sure this will take a while :D

- [x] Add Serverbound Chat Command (https://wiki.vg/Protocol#Chat_Command)

## Command Senders
- [x] Players can send Commands
- [x] Console can send Commands 
- [x]  RCON can send Commands

### Custom
- [x] /pumpkin | gives information about current pumpkin version
### Vanilla
https://minecraft.wiki/w/Commands#Available_in_Java_Edition
- [x] /[advancement](https://minecraft.wiki/w/Commands/advancement)
- [x] /[attribute](https://minecraft.wiki/w/Commands/attribute)
- [x] /[ban](https://minecraft.wiki/w/Commands/ban)
- [x] /[ban-ip](https://minecraft.wiki/w/Commands/ban-ip)
- [x] /[banlist](https://minecraft.wiki/w/Commands/banlist)
- [x] /[bossbar](https://minecraft.wiki/w/Commands/bossbar)
- [x] /[clear](https://minecraft.wiki/w/Commands/clear)
- [x] /[clone](https://minecraft.wiki/w/Commands/clone)
- [x] /[damage](https://minecraft.wiki/w/Commands/damage)
- [x] /[data](https://minecraft.wiki/w/Commands/data)
- [x] /[datapack](https://minecraft.wiki/w/Commands/datapack)
- [x] /[debug](https://minecraft.wiki/w/Commands/debug)
- [x] /[defaultgamemode](https://minecraft.wiki/w/Commands/defaultgamemode)
- [x] /[deop](https://minecraft.wiki/w/Commands/deop)
- [x] /[dialog](https://minecraft.wiki/w/Commands/dialog)
- [x] /[difficulty](https://minecraft.wiki/w/Commands/difficulty)
- [x] /[effect](https://minecraft.wiki/w/Commands/effect)
- [x] /[enchant](https://minecraft.wiki/w/Commands/enchant)
- [x] /[execute](https://minecraft.wiki/w/Commands/execute)
- [x] /[experience](https://minecraft.wiki/w/Commands/experience)
- [x] /[fetchprofile](https://minecraft.wiki/w/Commands/fetchprofile)
- [x] /[fill](https://minecraft.wiki/w/Commands/fill)
- [x] /[fillbiome](https://minecraft.wiki/w/Commands/fillbiome)
- [x] /[forceload](https://minecraft.wiki/w/Commands/forceload)
- [x] /[function](https://minecraft.wiki/w/Commands/function)
- [x] /[gamemode](https://minecraft.wiki/w/Commands/gamemode)
- [x] /[gamerule](https://minecraft.wiki/w/Commands/gamerule)
- [x] /[give](https://minecraft.wiki/w/Commands/give)
- [x] /[help](https://minecraft.wiki/w/Commands/help)
- [x] /[item](https://minecraft.wiki/w/Commands/item)
- [ ] /[jfr](https://minecraft.wiki/w/Commands/jfr)
- [x] /[kick](https://minecraft.wiki/w/Commands/kick)
- [x] /[kill](https://minecraft.wiki/w/Commands/kill)
- [x] /[list](https://minecraft.wiki/w/Commands/list)
- [x] /[locate](https://minecraft.wiki/w/Commands/locate)
- [x] /[loot](https://minecraft.wiki/w/Commands/loot)
- [x] /[me](https://minecraft.wiki/w/Commands/me)
- [x] /[msg](https://minecraft.wiki/w/Commands/msg)
- [x] /[op](https://minecraft.wiki/w/Commands/op)
- [x] /[pardon](https://minecraft.wiki/w/Commands/pardon)
- [x] /[pardon-ip](https://minecraft.wiki/w/Commands/pardon-ip)
- [x] /[particle](https://minecraft.wiki/w/Commands/particle)
- [ ] /[perf](https://minecraft.wiki/w/Commands/perf)
- [x] /[place](https://minecraft.wiki/w/Commands/place_(Java_Edition))
- [x] /[playsound](https://minecraft.wiki/w/Commands/playsound)
- [ ] /[publish](https://minecraft.wiki/w/Commands/publish)
- [x] /[random](https://minecraft.wiki/w/Commands/random)
- [x] /[recipe](https://minecraft.wiki/w/Commands/recipe)
- [x] /[reload](https://minecraft.wiki/w/Commands/reload)
- [x] /[return](https://minecraft.wiki/w/Commands/return)
- [x] /[ride](https://minecraft.wiki/w/Commands/ride)
- [x] /[rotate](https://minecraft.wiki/w/Commands/rotate)
- [x] /[save-all](https://minecraft.wiki/w/Commands/save-all)
- [x] /[save-off](https://minecraft.wiki/w/Commands/save-off)
- [x] /[save-on](https://minecraft.wiki/w/Commands/save-on)
- [x] /[say](https://minecraft.wiki/w/Commands/say)
- [x] /[schedule](https://minecraft.wiki/w/Commands/schedule)
- [x] /[scoreboard](https://minecraft.wiki/w/Commands/scoreboard)
- [x] /[seed](https://minecraft.wiki/w/Commands/seed)
- [x] /[setblock](https://minecraft.wiki/w/Commands/setblock)
- [x] /[setidletimeout](https://minecraft.wiki/w/Commands/setidletimeout)
- [x] /[setworldspawn](https://minecraft.wiki/w/Commands/setworldspawn)
- [x] /[spawnpoint](https://minecraft.wiki/w/Commands/spawnpoint)
- [x] /[spectate](https://minecraft.wiki/w/Commands/spectate)
- [x] /[spreadplayers](https://minecraft.wiki/w/Commands/spreadplayers)
- [x] /[stop](https://minecraft.wiki/w/Commands/stop)
- [x] /[stopsound](https://minecraft.wiki/w/Commands/stopsound)
- [x] /[summon](https://minecraft.wiki/w/Commands/summon)
- [x] /[tag](https://minecraft.wiki/w/Commands/tag)
- [x] /[team](https://minecraft.wiki/w/Commands/team)
- [x] /[teammsg](https://minecraft.wiki/w/Commands/teammsg)
- [x] /[teleport, tp](https://minecraft.wiki/w/Commands/teleport)
- [x] /[tell](https://minecraft.wiki/w/Commands/tell)
- [x] /[tellraw](https://minecraft.wiki/w/Commands/tellraw)
- [x] /[test](https://minecraft.wiki/w/Commands/test)
- [x] /[tick](https://minecraft.wiki/w/Commands/tick)
- [x] /[time](https://minecraft.wiki/w/Commands/time)
- [x] /[title](https://minecraft.wiki/w/Commands/title)
- [x] /[tm](https://minecraft.wiki/w/Commands/tm)
- [x] /[transfer](https://minecraft.wiki/w/Commands/transfer)
- [x] /[trigger](https://minecraft.wiki/w/Commands/trigger)
- [ ] /[unpublish](https://minecraft.wiki/w/Commands/unpublish)
- [x] /[version](https://minecraft.wiki/w/Commands/version)
- [x] /[w](https://minecraft.wiki/w/Commands/w)
- [x] /[waypoint](https://minecraft.wiki/w/Commands/waypoint)
- [x] /[weather](https://minecraft.wiki/w/Commands/weather)
- [x] /[whitelist](https://minecraft.wiki/w/Commands/whitelist)
- [x] /[worldborder](https://minecraft.wiki/w/Commands/worldborder)
- [x] /[xp](https://minecraft.wiki/w/Commands/xp)

## Config
- [x] Option to Enable or Disable every single Command, We may so should use the config to set the permission

**Comment by user622628252416** [comment]
Hi!
As far as I can tell there is no command parser yet? Minecraft uses [Brigadier](https://github.com/Mojang/brigadier) (which is MIT licensed, but in Java ofc), would you appreciate if I reimplemented that in rust?

**Comment by Snowiiii** [comment]
> Hi! As far as I can tell there is no command parser yet? Minecraft uses [Brigadier](https://github.com/Mojang/brigadier) (which is MIT licensed, but in Java ofc), would you appreciate if I reimplemented that in rust?

Hey, Yeah i actually had such an idea aswell, Would be great when you can do that. Feel free to use custom concepts you don't have to exactly match Brigadier

**Comment by user622628252416** [comment]
Nvm, I just found [this existing rust port](https://crates.io/crates/brigadier_rs)

**Comment by Snowiiii** [comment]
> Nvm, I just found [this existing rust port](https://crates.io/crates/brigadier_rs). What's your policy on using external crates such as this one?

Hey, The create is unmaintend, And i also would like to use an own solution

**Comment by user622628252416** [comment]
I see. I'll have a look at what I can do

**Comment by Wundero** [comment]
Something to note for the command parser is that 1.21 introduced the `@n` selector for targetting the nearest entity that matches the selector. For players, it is equivalent to `@p`, but will matter when commands which target non-player entities are introduced later on. 

Reference documentation for target selectors: https://minecraft.wiki/w/Target_selectors

**Comment by OfficialKris** [comment]
Are we implementing only JE commands? This list includes commands not found in JE.

**Comment by glitchy-sk8k9** [comment]
> Are we implementing only JE commands? This list includes commands not found in JE.

I see /ability in the list, that's BE. Probably so, maybe we will get completely different commands.

**Comment by Snowiiii** [comment]
> > Are we implementing only JE commands? This list includes commands not found in JE.
> 
> I see /ability in the list, that's BE. Probably so, maybe we will get completely different commands.

You right, I removed it since we only want to support Java Commands.
*at least for now*

**Comment by glitchy-sk8k9** [comment]
> > > Are we implementing only JE commands? This list includes commands not found in JE.
> > 
> > 
> > I see /ability in the list, that's BE. Probably so, maybe we will get completely different commands.
> 
> You right, I removed it since we only want to support Java Commands. _at least for now_

rip

**Comment by timitoerner** [comment]
I have gone through the wiki and found even more commands that are exclusive to bedrock or education edition:
This is a new _only JE commands_ list:

- [ ] /[advancement](https://minecraft.wiki/w/Commands/advancement)
- [ ] /[attribute](https://minecraft.wiki/w/Commands/attribute)
- [ ] /[ban](https://minecraft.wiki/w/Commands/ban)
- [ ] /[ban-ip](https://minecraft.wiki/w/Commands/ban-ip)
- [ ] /[banlist](https://minecraft.wiki/w/Commands/banlist)
- [ ] /[bossbar](https://minecraft.wiki/w/Commands/bossbar)
- [ ] /[clear](https://minecraft.wiki/w/Commands/clear)
- [ ] /[clone](https://minecraft.wiki/w/Commands/clone)
- [ ] /[damage](https://minecraft.wiki/w/Commands/damage)
- [ ] /[data](https://minecraft.wiki/w/Commands/data)
- [ ] /[datapack](https://minecraft.wiki/w/Commands/datapack)
- [ ] /[debug](https://minecraft.wiki/w/Commands/debug)
- [ ] /[defaultgamemode](https://minecraft.wiki/w/Commands/defaultgamemode)
- [ ] /[deop](https://minecraft.wiki/w/Commands/deop)
- [ ] /[difficulty](https://minecraft.wiki/w/Commands/difficulty)
- [ ] /[effect](https://minecraft.wiki/w/Commands/effect)
- [ ] /[enchant](https://minecraft.wiki/w/Commands/enchant)
- [ ] /[execute](https://minecraft.wiki/w/Commands/execute)
- [ ] /[experience](https://minecraft.wiki/w/Commands/experience)
- [ ] /[fill](https://minecraft.wiki/w/Commands/fill)
- [ ] /[fillbiome](https://minecraft.wiki/w/Commands/fillbiome)
- [ ] /[forceload](https://minecraft.wiki/w/Commands/forceload)
- [ ] /[function](https://minecraft.wiki/w/Commands/function)
- [x] /[gamemode](https://minecraft.wiki/w/Commands/gamemode)
- [ ] /[gamerule](https://minecraft.wiki/w/Commands/gamerule)
- [x] /[give](https://minecraft.wiki/w/Commands/give)
- [ ] /[help](https://minecraft.wiki/w/Commands/help)
- [ ] /[item](https://minecraft.wiki/w/Commands/item)
- [ ] /[jfr](https://minecraft.wiki/w/Commands/jfr)
- [x] /[kick](https://minecraft.wiki/w/Commands/kick)
- [x] /[kill](https://minecraft.wiki/w/Commands/kill)
- [x] /[list](https://minecraft.wiki/w/Commands/list)
- [ ] /[locate](https://minecraft.wiki/w/Commands/locate)
- [ ] /[loot](https://minecraft.wiki/w/Commands/loot)
- [ ] /[me](https://minecraft.wiki/w/Commands/me)
- [ ] /[msg](https://minecraft.wiki/w/Commands/msg)
- [ ] /[op](https://minecraft.wiki/w/Commands/op)
- [ ] /[pardon](https://minecraft.wiki/w/Commands/pardon)
- [ ] /[pardon-ip](https://minecraft.wiki/w/Commands/pardon-ip)
- [ ] /[particle](https://minecraft.wiki/w/Commands/particle)
- [ ] /[perf](https://minecraft.wiki/w/Commands/perf)
- [ ] /[place](https://minecraft.wiki/w/Commands/place_(Java_Edition))
- [ ] /[playsound](https://minecraft.wiki/w/Commands/playsound)
- [ ] /[random](https://minecraft.wiki/w/Commands/random)
- [ ] /[recipe](https://minecraft.wiki/w/Commands/recipe)
- [ ] /[reload](https://minecraft.wiki/w/Commands/reload)
- [ ] /[return](https://minecraft.wiki/w/Commands/return)
- [ ] /[ride](https://minecraft.wiki/w/Commands/ride)
- [ ] /[rotate](https://minecraft.wiki/w/Commands/rotate)
- [ ] /[save-all](https://minecraft.wiki/w/Commands/save-all)
- [ ] /[save-off](https://minecraft.wiki/w/Commands/save-off)
- [ ] /[save-on](https://minecraft.wiki/w/Commands/save-on)
- [x] /[say](https://minecraft.wiki/w/Commands/say)
- [ ] /[schedule](https://minecraft.wiki/w/Commands/schedule)
- [ ] /[scoreboard](https://minecraft.wiki/w/Commands/scoreboard)
- [x] /[seed](https://minecraft.wiki/w/Commands/seed)
- [x] /[setblock](https://minecraft.wiki/w/Commands/setblock)
- [ ] /[setidletimeout](https://minecraft.wiki/w/Commands/setidletimeout)
- [ ] /[setworldspawn](https://minecraft.wiki/w/Commands/setworldspawn)
- [ ] /[spawnpoint](https://minecraft.wiki/w/Commands/spawnpoint)
- [ ] /[spectate](https://minecraft.wiki/w/Commands/spectate)
- [ ] /[spreadplayers](https://minecraft.wiki/w/Commands/spreadplayers)
- [x] /[stop](https://minecraft.wiki/w/Commands/stop)
- [ ] /[stopsound](https://minecraft.wiki/w/Commands/stopsound)
- [ ] /[summon](https://minecraft.wiki/w/Commands/summon)
- [ ] /[tag](https://minecraft.wiki/w/Commands/tag)
- [ ] /[team](https://minecraft.wiki/w/Commands/team)
- [ ] /[teammsg](https://minecraft.wiki/w/Commands/teammsg)
- [x] /[teleport, tp](https://minecraft.wiki/w/Commands/teleport)
- [ ] /[tell](https://minecraft.wiki/w/Commands/tell)
- [ ] /[tellraw](https://minecraft.wiki/w/Commands/tellraw)
- [ ] /[tick](https://minecraft.wiki/w/Commands/tick)
- [x] /[time](https://minecraft.wiki/w/Commands/time)
- [ ] /[title](https://minecraft.wiki/w/Commands/title)
- [ ] /[tm](https://minecraft.wiki/w/Commands/tm)
- [ ] /[transfer](https://minecraft.wiki/w/Commands/transfer)
- [ ] /[trigger](https://minecraft.wiki/w/Commands/trigger)
- [ ] /[w](https://minecraft.wiki/w/Commands/w)
- [ ] /[weather](https://minecraft.wiki/w/Commands/weather)
- [ ] /[whitelist](https://minecraft.wiki/w/Commands/whitelist)
- [x] /[worldborder](https://minecraft.wiki/w/Commands/worldborder)
- [ ] /[xp](https://minecraft.wiki/w/Commands/xp)

Please correct me if I am wrong

**Comment by Snowiiii** [comment]
> I have gone through the wiki and found even more commands that are exclusive to bedrock or education edition: This is a new _only JE commands_ list:
> 
>     * [ ]  /[advancement](https://minecraft.wiki/w/Commands/advancement)
> 
>     * [ ]  /[attribute](https://minecraft.wiki/w/Commands/attribute)
> 
>     * [ ]  /[ban](https://minecraft.wiki/w/Commands/ban)
> 
>     * [ ]  /[ban-ip](https://minecraft.wiki/w/Commands/ban-ip)
> 
>     * [ ]  /[banlist](https://minecraft.wiki/w/Commands/banlist)
> 
>     * [ ]  /[bossbar](https://minecraft.wiki/w/Commands/bossbar)
> 
>     * [ ]  /[clear](https://minecraft.wiki/w/Commands/clear)
> 
>     * [ ]  /[clone](https://minecraft.wiki/w/Commands/clone)
> 
>     * [ ]  /[damage](https://minecraft.wiki/w/Commands/damage)
> 
>     * [ ]  /[data](https://minecraft.wiki/w/Commands/data)
> 
>     * [ ]  /[datapack](https://minecraft.wiki/w/Commands/datapack)
> 
>     * [ ]  /[debug](https://minecraft.wiki/w/Commands/debug)
> 
>     * [ ]  /[defaultgamemode](https://minecraft.wiki/w/Commands/defaultgamemode)
> 
>     * [ ]  /[deop](https://minecraft.wiki/w/Commands/deop)
> 
>     * [ ]  /[difficulty](https://minecraft.wiki/w/Commands/difficulty)
> 
>     * [ ]  /[effect](https://minecraft.wiki/w/Commands/effect)
> 
>     * [ ]  /[enchant](https://minecraft.wiki/w/Commands/enchant)
> 
>     * [ ]  /[execute](https://minecraft.wiki/w/Commands/execute)
> 
>     * [ ]  /[experience](https://minecraft.wiki/w/Commands/experience)
> 
>     * [ ]  /[fill](https://minecraft.wiki/w/Commands/fill)
> 
>     * [ ]  /[fillbiome](https://minecraft.wiki/w/Commands/fillbiome)
> 
>     * [ ]  /[forceload](https://minecraft.wiki/w/Commands/forceload)
> 
>     * [ ]  /[function](https://minecraft.wiki/w/Commands/function)
> 
>     * [x]  /[gamemode](https://minecraft.wiki/w/Commands/gamemode)
> 
>     * [ ]  /[gamerule](https://minecraft.wiki/w/Commands/gamerule)
> 
>     * [x]  /[give](https://minecraft.wiki/w/Commands/give)
> 
>     * [ ]  /[help](https://minecraft.wiki/w/Commands/help)
> 
>     * [ ]  /[item](https://minecraft.wiki/w/Commands/item)
> 
>     * [ ]  /[jfr](https://minecraft.wiki/w/Commands/jfr)
> 
>     * [x]  /[kick](https://minecraft.wiki/w/Commands/kick)
> 
>     * [x]  /[kill](https://minecraft.wiki/w/Commands/kill)
> 
>     * [x]  /[list](https://minecraft.wiki/w/Commands/list)
> 
>     * [ ]  /[locate](https://minecraft.wiki/w/Commands/locate)
> 
>     * [ ]  /[loot](https://minecraft.wiki/w/Commands/loot)
> 
>     * [ ]  /[me](https://minecraft.wiki/w/Commands/me)
> 
>     * [ ]  /[msg](https://minecraft.wiki/w/Commands/msg)
> 
>     * [ ]  /[op](https://minecraft.wiki/w/Commands/op)
> 
>     * [ ]  /[pardon](https://minecraft.wiki/w/Commands/pardon)
> 
>     * [ ]  /[pardon-ip](https://minecraft.wiki/w/Commands/pardon-ip)
> 
>     * [ ]  /[particle](https://minecraft.wiki/w/Commands/particle)
> 
>     * [ ]  /[perf](https://minecraft.wiki/w/Commands/perf)
> 
>     * [ ]  /[place](https://minecraft.wiki/w/Commands/place_(Java_Edition))
> 
>     * [ ]  /[playsound](https://minecraft.wiki/w/Commands/playsound)
> 
>     * [ ]  /[random](https://minecraft.wiki/w/Commands/random)
> 
>     * [ ]  /[recipe](https://minecraft.wiki/w/Commands/recipe)
> 
>     * [ ]  /[reload](https://minecraft.wiki/w/Commands/reload)
> 
>     * [ ]  /[return](https://minecraft.wiki/w/Commands/return)
> 
>     * [ ]  /[ride](https://minecraft.wiki/w/Commands/ride)
> 
>     * [ ]  /[rotate](https://minecraft.wiki/w/Commands/rotate)
> 
>     * [ ]  /[save-all](https://minecraft.wiki/w/Commands/save-all)
> 
>     * [ ]  /[save-off](https://minecraft.wiki/w/Commands/save-off)
> 
>     * [ ]  /[save-on](https://minecraft.wiki/w/Commands/save-on)
> 
>     * [x]  /[say](https://minecraft.wiki/w/Commands/say)
> 
>     * [ ]  /[schedule](https://minecraft.wiki/w/Commands/schedule)
> 
>     * [ ]  /[scoreboard](https://minecraft.wiki/w/Commands/scoreboard)
> 
>     * [x]  /[seed](https://minecraft.wiki/w/Commands/seed)
> 
>     * [x]  /[setblock](https://minecraft.wiki/w/Commands/setblock)
> 
>     * [ ]  /[setidletimeout](https://minecraft.wiki/w/Commands/setidletimeout)
> 
>     * [ ]  /[setworldspawn](https://minecraft.wiki/w/Commands/setworldspawn)
> 
>     * [ ]  /[spawnpoint](https://minecraft.wiki/w/Commands/spawnpoint)
> 
>     * [ ]  /[spectate](https://minecraft.wiki/w/Commands/spectate)
> 
>     * [ ]  /[spreadplayers](https://minecraft.wiki/w/Commands/spreadplayers)
> 
>     * [x]  /[stop](https://minecraft.wiki/w/Commands/stop)
> 
>     * [ ]  /[stopsound](https://minecraft.wiki/w/Commands/stopsound)
> 
>     * [ ]  /[summon](https://minecraft.wiki/w/Commands/summon)
> 
>     * [ ]  /[tag](https://minecraft.wiki/w/Commands/tag)
> 
>     * [ ]  /[team](https://minecraft.wiki/w/Commands/team)
> 
>     * [ ]  /[teammsg](https://minecraft.wiki/w/Commands/teammsg)
> 
>     * [x]  /[teleport, tp](https://minecraft.wiki/w/Commands/teleport)
> 
>     * [ ]  /[tell](https://minecraft.wiki/w/Commands/tell)
> 
>     * [ ]  /[tellraw](https://minecraft.wiki/w/Commands/tellraw)
> 
>     * [ ]  /[tick](https://minecraft.wiki/w/Commands/tick)
> 
>     * [x]  /[time](https://minecraft.wiki/w/Commands/time)
> 
>     * [ ]  /[title](https://minecraft.wiki/w/Commands/title)
> 
>     * [ ]  /[tm](https://minecraft.wiki/w/Commands/tm)
> 
>     * [ ]  /[transfer](https://minecraft.wiki/w/Commands/transfer)
> 
>     * [ ]  /[trigger](https://minecraft.wiki/w/Commands/trigger)
> 
>     * [ ]  /[w](https://minecraft.wiki/w/Commands/w)
> 
>     * [ ]  /[weather](https://minecraft.wiki/w/Commands/weather)
> 
>     * [ ]  /[whitelist](https://minecraft.wiki/w/Commands/whitelist)
> 
>     * [x]  /[worldborder](https://minecraft.wiki/w/Commands/worldborder)
> 
>     * [ ]  /[xp](https://minecraft.wiki/w/Commands/xp)
> 
> 
> Please correct me if I am wrong

looks good. thank you :D

**Comment by Q2297045667** [comment]
I noticed that there is no`/tp`command above.I think it would be a very convenient command when testing on the server.

**Comment by suprohub** [comment]
We have some new commands. Can you check it alex? (Make done in checkbox)

**Comment by Snowiiii** [comment]
> We have some new commands. Can you check it alex? (Make done in checkbox)

Looks like everything is right checked

**Comment by suprohub** [comment]
Transfer for ecample

**Comment by DirefulBelt6803** [comment]
Minecraft Java Edition supposedly also has a secret developer mode which has these commands (Information may be hard to find on these):
* [ ]  /debugpath
* [ ]  /debugmobspawning
* [ ]  /spawn_armor_trims
* [ ]  /serverpack
* [ ]  /warden_spawn_tracker
* [ ]  /raid
* [ ]  /test
* [ ]  /debugconfig

Source:
https://www.youtube.com/watch?v=Rt_hy6FF_P4

There is a mod to enable developer tools
https://modrinth.com/mod/dev-tools-unlocker/

**Comment by LuciCrack** [comment]
I've found the /give successfully works, but it is **incomplete**, It can't handle a **list of components** ([https://minecraft.wiki/w/Data_component_format](url)) for the item argument, which I think is the most important part of the command.
I suggest marking the command as W.I.P or something.

(Should I open an issue on this?)

Here are some wiki links that might be useful for implementing this feature: 
[https://minecraft.wiki/w/Commands/give#Arguments](url) 
[https://minecraft.wiki/w/Argument_types#item_stack](url)

**Comment by Laptop59** [comment]
`/data` is not complete at all. The current implementation only has `/data get entity <selector>`. `/data` is much more complex than that.

**Comment by LegendsOfXania** [comment]
``/dialog`` is not in the list? Or maybe I missed it

**Comment by Laptop59** [comment]
Well, I don't see it either, probably because it's a new command (it looks like commands introduced from 1.21.5 or newer are not in the list)

**Comment by Snowiiii** [comment]
> `/dialog` is not in the list? Or maybe I missed it

Just added it to the list, was introduced in 1.21.6

**Comment by Laptop59** [comment]
what about /test, /version, /waypoint and /fetchprofile?

**Comment by Alleexxi** [comment]
Hey, i would like to ask why publish and unpublish are on the list? They shouldnt exist on the server iirc.

**Comment by codeman4033** [comment]
Don't forget about /swing

**Comment by Snowiiii** [comment]
🎉
